on: [push]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    name: Runs e2e tests with Playwright
    steps:
    - name: Playwright test suite
      uses: SophieDeBenedetto/playwright-test-service-prototype@v1.7
