on: [push]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    name: Runs e2e tests with Playwright
    steps:
    - name: Playwright test suite
      uses: SophieDeBenedetto/playwright-test-service-prototype@v1.11
    - name: upload artifacts
      if: ${{ always() }} # could be if: ${{ failure() }} to only upload artifacts when previous step of running playwright tests fails
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: /app/artifact/results.json # or path/to/artifact
